### ISSUE TITLE
Slightly unclear description of lodash in README.md

### ISSUE THREAD

**Issue by ljmatkins** [erasaur/meteor-lodash#1]
"A wrapper for Lo-Dash v3.1.0, a utility library built on top of Underscore.js."

implies that lodash uses underscore, rather than replaces it. It might be clearer if it was changed to something like:

"A wrapper for Lo-Dash v3.1.0, a replacement for the Underscore.js utility library."

**Comment by erasaur** [comment]
You're right, it is misleading. I think what I meant was that Lo-Dash is a superset of Underscore. I'll go ahead and change the README in a bit. Thanks @ljmatkins.
