### ISSUE TITLE
lodash 3.2

### ISSUE THREAD

**Issue by luglio7** [erasaur/meteor-lodash#2]
Lodash 3.2 is out, can you update ?

**Comment by erasaur** [comment]
@luglio7 Yes, thanks for the heads up! Lo-Dash updates pretty quickly, wow.

**Comment by jdalton** [comment]
Just a heads up, lodash will now be updating weekly (or close to that), so there shouldn't be a long delay (as seen with 2.4.1 to 3.0) again. 

I'm not familiar with the package setup but if there's a way to point to a remote lodash (maybe leveraging `npm info lodash@"^3.0.0" dist.tarball` that may help)

**Comment by jdalton** [comment]
I'm not familiar with the package set up but if there's a way to point to a remote lodash (maybe leveraging `npm info lodash@"^3.0.0" dist.tarball` that may help)

**Comment by erasaur** [comment]
Awesome, thanks for the heads up. In that case, would you like to maintain an official Lo-Dash package, as it seems to be gaining traction in the Meteor community? Maybe @dandv has something to say about getting an official package set up for you, if you are interested.

**Comment by jdalton** [comment]
I'm up for it though not sure about best practices for meteor packages. It looks like you specify an [npm package version](https://github.com/erasaur/meteor-lodash/blob/6456f10816ab333eeffe1bbb8ebbe308176e1781/package.js#L8). Does that support version ranges like `^3.0.0`? If so is there a way to simply use  the npm version for both server and browser side (the index.js in the npm package is the full lodash modern build complete with UMD).

Also for those interested https://github.com/meteor/meteor/issues/1009.

**Comment by jdalton** [comment]
Also for those interested https://github.com/meteor/meteor/issues/1009.

**Comment by erasaur** [comment]
I believe ranges are supported. But I think @dandv and a few others have come up with a better way to integrate third libraries with their [autopublish](https://github.com/MeteorPackaging/autopublish.meteor.com) tool, though I admit I've had little time to look into it yet. In any case, the idea is that there should be little to no work on your part. I'll let Dan comment on this, before I say something absolutely erroneous ;-)

I saw your tweet about Lo-Dash integration into Meteor -- very excited for the change. I wonder how long the process will take though, and in the meantime developers like myself will need a wrapper package for Lo-Dash.

**Comment by erasaur** [comment]
@jdalton Looks like it might be simpler for me to maintain this package until Meteor replaces underscore. I've added lodash as a submodule so it should be easy to update to new versions. Hopefully this is ok with you, and thanks for your willingness to help.
