### ISSUE TITLE
docs says _ will refer to lodash

### ISSUE THREAD

**Issue by pihentagy** [erasaur/meteor-lodash#3]
If I add your project, and open a console in my meteor app:

```
lodash.VERSION
"3.3.0"
_.VERSION
"1.5.2"
```

**Comment by erasaur** [comment]
I haven't gotten much time to investigate but it looks like the underscore package is somehow overriding the exported `_` variable. It would be best to define `_ = lodash` globally in your code to be safe.

**Comment by pihentagy** [comment]
Would you mind altering the sentence "The package exports _ and lodash as two global variables." in the readme?

**Comment by erasaur** [comment]
I've added a note about the potential conflict in the README -- feel free to let me know if there's anything else.

**Comment by pihentagy** [comment]
thanks
