### ISSUE TITLE
Could I use "underscore" and "lodash" in one app?

### ISSUE THREAD

**Issue by thearabbit** [erasaur/meteor-lodash#5]
I used `underscore` in my app.
And now I want to try `lodash`.
Its conflict or not (I use `_` keyword for `underscore` and `lodash` keyword for `lodash`?

**Comment by thearabbit** [comment]
Or I must remove the `underscore` package?

**Comment by erasaur** [comment]
You should be able to use the `lodash` keyword without removing `underscore`. It's probably a good idea to choose one or the other though.
