### ISSUE TITLE
Hello there,

### ISSUE THREAD

**Issue by trusktr** [erasaur/meteor-lodash#7]
May I convince you to try [`rocket:module`](https://github.com/meteor-rocket/module)? It will share your lodash from NPM with all the Meteor packages of a given Meteor application at the same time so you don't have to wrap lodash from NPM inside of your meteor-lodash package.

This reduces the amount of maintenance that you need to do to publish new versions of lodash by _100%_, while affording other Meteor package developers the freedom to use other NPM packages that may also depend on lodash from NPM.

There's no way you'd want to wrap all the NPM packages that depend on lodash from NPM into your meteor-lodash package.

`rocket:module` allows for Meteor packages to get and share external libraries from NPM, avoiding the pollution of the [Atmosphere](https://atmospherejs.com) caused by Meteor packages that depend on the same NPM packages. Meteor's default behavior is to compile, save, and store an NPM package into each Meteor package during publication of the Meteor packages onto Atmosphere.

For example, if 10 Meteor packages in your application depend on 10 libraries from NPM, and those 10 NPM libraries all depend on React from NPM, then your application now has 10 copies of the React library...

_That's 10 singleton React objects in your application._

React isn't meant to be used that way. That's way worse than having 10 versions of jQuery in the same application: `$`, `$1`, `$2`, `$3`, `$4`, `$5`, `$6`, `$7`, `$8`, `$9`, and `$10`.

To help the cause, use `rocket:module` to specify all your NPM dependencies. Once you've done that, `rocket:module` will handle the sharing of those NPM modules across your app's Meteor packages.

**Comment by erasaur** [comment]
Hey there! This is a pretty neat idea, and I'd be glad to try it out personally when it reaches v1. Until your package gets greater adoption, however, it would probably be best to keep this package as-is, since many developers depend on this package and may not want to make the switch to `rocket:module` quite yet. Maybe you can share your package on crater.io or the forums and see what people think -- the issue tracker here is probably not nearly as effective. Cheers!

**Comment by trusktr** [comment]
@erasaur For sure. :) Well, the great thing is that if you were to use `rocket:module` when it's v1, your users wouldn't notice. They'd continue using the global that your package exports. The only change would be behind the scenes: the source for where your package gets lodash.
